Repository Bismay5467/ExamArchive, pull requests merged in 2024-07, with the labels that each got.

#36 ✨ ui : search page
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/Root.tsx
  client/src/assets/images/features-03-image-01.png
  client/src/assets/images/features-03-image-02.png
  client/src/assets/images/features-03-image-03.png
  client/src/assets/images/hero-image-01.jpg
  client/src/assets/images/testimonial-01.jpg
  client/src/assets/images/testimonial-02.jpg
  client/src/assets/images/testimonial-03.jpg
  client/src/components/SearchBar/SearchBar.tsx
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/components/SearchFilterSheet/SearchFilterSheet.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/ui/sheet.tsx
  client/src/constants/search.ts
  client/src/constants/shared.ts
  client/src/hooks/useSearch.tsx
  client/src/index.css
  client/src/pages/Home/Testimonials/Testimonials.tsx
  client/src/pages/Home/Zigzag/Zigzag.tsx
  client/src/pages/Search/Filter/AsideFilter.tsx
  client/src/pages/Search/Filter/DrawerFilter.tsx
  client/src/pages/Search/Filter/FilterForm/FilterForm.tsx
  client/src/pages/Search/Placeholders/InitialDisplay.tsx
  client/src/pages/Search/Placeholders/NoResults.tsx
  client/src/pages/Search/ResultCard/ResultCard.tsx
  client/src/pages/Search/Search.tsx
  client/src/pages/Search/Shimmer/Shimmer.tsx
  client/src/types/search.ts
  client/src/utils/axiosReqObjects/search.ts
  client/src/utils/helpers/index.ts
  client/tailwind.config.ts
  server/app.ts
  server/controllers/search/GetPapers.ts
Labels: frontend

#41 🐛 bug : bugs in search filter resolved and ui reverted partially
  client/package-lock.json
  client/package.json
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/components/SearchFilterSheet/SearchFilterSheet.tsx
  client/src/hooks/useSearch.tsx
  client/src/pages/Search/ResultCard/ResultCard.tsx
  client/src/types/search.ts
  server/router/search/schema.ts
  server/utils/search/getter.ts
Labels: frontend

#37 ✨[UI] Preview
  client/package-lock.json
  client/package.json
  client/src/components/Dropdown.tsx
  client/src/components/ReportModal/ReportModal.tsx
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/Skeleton.tsx
  client/src/components/Tags.tsx
  client/src/components/TagsEditor/TagsEditor.tsx
  client/src/components/WarningModal/WarningModal.tsx
  client/src/constants/routes.ts
  client/src/constants/shared.ts
  client/src/pages/Preview/Comments/CommentBox/ParentCommentBox.tsx
  client/src/pages/Preview/Comments/CommentBox/ReplyCommentBox.tsx
  client/src/pages/Preview/Comments/CommentForm/ParentCommentForm.tsx
  client/src/pages/Preview/Comments/CommentForm/ReplyCommentForm.tsx
  client/src/pages/Preview/Comments/Comments.tsx
  client/src/pages/Preview/Comments/Skeleton/Skeleton.tsx
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Preview/PreviewContent/BasicInfo/BasicInfo.tsx
  client/src/pages/Preview/PreviewContent/BookmarksModal/BookmarksModal.tsx
  client/src/pages/Preview/PreviewContent/HeaderStrip/HeaderStrip.tsx
  client/src/pages/Preview/PreviewContent/PreviewContent.tsx
  client/src/pages/Preview/PreviewContent/RatingPopover/RatingPopover.tsx
  client/src/pages/Preview/PreviewContent/RatingSection/RatingSection.tsx
  client/src/pages/Preview/PreviewContent/TagsSection/TagsSection.tsx
  client/src/pages/Preview/Shimmer/Shimmer.tsx
  client/src/pages/Search/ResultCard/ResultCard.tsx
  client/src/types/comments.ts
  client/src/types/file.ts
  client/src/types/ratiing.ts
  client/src/utils/axiosReqObjects/file.ts
  client/src/utils/axiosReqObjects/index.ts
  client/src/utils/axiosReqObjects/rating.ts
  server/controllers/filePreview/data/DownloadCount.ts
  server/controllers/filePreview/data/EditTags.ts
  server/controllers/filePreview/data/GetFile.ts
  server/controllers/filePreview/data/Rating.ts
  server/controllers/filePreview/data/ViewCount.ts
Labels: backend, frontend

#43 ✨ ui : ui revamped for bookmark and upload pages
  client/package-lock.json
  client/src/components/Pagination/RenderItems.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/TabularView/TabularFileView.tsx
  client/src/components/TabularView/TabularFolderView.tsx
  client/src/pages/DashBoard/Bookmarks/Bookmarks.tsx
  client/src/pages/DashBoard/FileUpload/FileUpload.tsx
  client/src/pages/Preview/Comments/Comments.tsx
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Preview/PreviewContent/HeaderStrip/HeaderStrip.tsx
  client/src/pages/Preview/PreviewContent/PDFViewer/PDFViewer.tsx
  client/src/pages/Preview/PreviewContent/PreviewContent.tsx
  client/src/pages/Preview/Shimmer/Shimmer.tsx
  client/src/types/comments.ts
Labels: frontend

#42 file preview fixed and view count and download count api integrated
  client/src/pages/Preview/PreviewContent/BasicInfo/BasicInfo.tsx
  client/src/pages/Preview/PreviewContent/HeaderStrip/HeaderStrip.tsx
  client/src/pages/Preview/PreviewContent/PDFViewer/PDFViewer.tsx
  client/src/pages/Preview/PreviewContent/PreviewContent.tsx
  client/src/pages/Preview/PreviewContent/RatingSection/RatingSection.tsx
  client/src/pages/Preview/Shimmer/Shimmer.tsx
  client/src/types/file.ts
  client/src/utils/axiosReqObjects/file.ts
  server/controllers/filePreview/data/DownloadCount.ts
  server/controllers/filePreview/data/Rating.ts
  server/controllers/filePreview/data/ViewCount.ts
  server/models/question.ts
Labels: frontend

#44 🚀 feat : superadmin routes
  client/src/components/Sidebar/Sidebar.tsx
  client/src/constants/shared.ts
  server/constants/constants/report.ts
  server/controllers/folders/GetFiles.ts
  server/controllers/report/GetFlaggedComment.ts
  server/controllers/report/ReportContent.ts
  server/controllers/report/ViewReport.ts
  server/controllers/report/index.ts
  server/emails/ReportNotification.tsx
  server/models/report.ts
  server/router/report/router.ts
  server/router/report/schema.ts
  server/utils/folders/sanitizeFilesInfo.ts
  server/utils/report/getter.ts
Labels: backend

#46 🚀 dark mode
  client/package-lock.json
  client/package.json
  client/src/components/Dropdown.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/ProtectedRoute.tsx
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/components/SearchFilterSheet/SearchFilterSheet.tsx
  client/src/components/Sidebar/MobileSidebar/MobileSidebar.tsx
  client/src/components/Sidebar/NavCard/NavCard.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/TagsEditor/TagsEditor.tsx
  client/src/components/ui/card-hover-effect.tsx
  client/src/pages/Auth/Auth.tsx
  client/src/pages/DashBoard/Bookmarks/Bookmarks.tsx
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/Forbidden.tsx
  client/src/pages/Home/Header/Header.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/Testimonials/Testimonials.tsx
  client/src/pages/Preview/BasicInfo/BasicInfo.tsx
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Preview/RatingSection/RatingSection.tsx
  client/src/pages/Preview/TagsSection/TagsSection.tsx
  client/src/pages/Search/Placeholders/InitialDisplay.tsx
  client/src/pages/Search/Placeholders/NoResults.tsx
  client/src/pages/Search/ResultCard/ResultCard.tsx
  server/controllers/search/GetSubjectFilters.ts
Labels: frontend

#47 Bug Fixes
  client/index.html
  client/public/favicon.svg
  client/public/logo-no-bg.png
  client/src/assets/Logo.png
  client/src/assets/LogoBanner.png
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/components/SearchFilterSheet/SearchFilterSheet.tsx
  client/src/components/ui/sheet.tsx
  client/src/pages/Preview/BasicInfo/BookmarksModal/BookmarksModal.tsx
  client/src/pages/Preview/Comments/CommentBox/ParentCommentBox.tsx
  client/src/pages/Preview/Comments/CommentBox/ReplyCommentBox.tsx
  client/src/pages/Preview/Comments/CommentForm/ParentCommentForm.tsx
Labels: frontend

#48 🐛 bug : auth fixed
  client/src/Root.tsx
  client/src/components/SearchFilterSheet/OptionGroup/OptionGroup.tsx
  client/src/pages/Auth/AuthTabs/Login/Login.tsx
  client/src/pages/Home/Hero/Hero.tsx
Labels: frontend
