Repository Bismay5467/ExamArchive, pull requests merged in 2024-06, with the labels that each got.

#8 ✨ feat : search functionality implemented
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/Root.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/components/ui/select.tsx
  client/src/components/ui/spinner.tsx
  client/src/constants/routes.ts
  client/src/constants/search.ts
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Search/Filter/AsideFilter.tsx
  client/src/pages/Search/Filter/DrawerFilter.tsx
  client/src/pages/Search/Filter/FilterForm/FilterForm.tsx
  client/src/pages/Search/ResultCard/ResultCard.tsx
  client/src/pages/Search/Search.tsx
  client/src/types/index.ts
  client/src/types/search.ts
  client/src/utils/axiosReqObjects/index.ts
  client/src/utils/axiosReqObjects/search.ts
  client/src/utils/fetcher/fetcher.ts
  client/src/utils/swr/fetcher.ts
Labels: frontend

#9 ✨ feat : password based authentication system
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/favicon.svg
  client/public/vite.svg
  client/src/Root.tsx
  client/src/assets/LoginImage.jpg
  client/src/assets/ResetImage.jpg
  client/src/components/ModeToggle.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/components/ui/avatar.tsx
  client/src/components/ui/checkbox.tsx
  client/src/components/ui/input-otp.tsx
  client/src/components/ui/label.tsx
  client/src/components/ui/sonner.tsx
  client/src/constants/auth.ts
  client/src/constants/routes.ts
  client/src/constants/statusCodes/index.ts
  client/src/hooks/.gitkeep
  client/src/hooks/theme-provider.tsx
  client/src/hooks/useAuth.tsx
  client/src/hooks/useMultiStepForm.ts
  client/src/hooks/useTheme.tsx
  client/src/main.tsx
  client/src/pages/404/Error.tsx
  client/src/pages/Auth/Login/Login.tsx
  client/src/pages/Auth/Reset/Email/Email.tsx
  client/src/pages/Auth/Reset/Reset.tsx
  client/src/pages/Auth/Reset/Update/Update.tsx
  client/src/pages/Auth/Signup/SignUpFormElements/AccountForm.tsx
  client/src/pages/Auth/Signup/SignUpFormElements/OTPForm.tsx
  client/src/pages/Auth/Signup/Signup.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Search/Search.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/schemas/authSchema.ts
  client/src/types/auth.ts
  client/src/types/theme.ts
  client/src/utils/axiosReqObjects/auth.ts
  client/src/utils/axiosReqObjects/index.ts
  client/tailwind.config.ts
Labels: frontend

#17 ✨ enhancement : upload route fixed
  client/.eslintrc.cjs
  client/vite.config.ts
  server/app.ts
  server/constants/constants/upload.ts
  server/controllers/upload/NotificationWebhook.ts
  server/controllers/upload/UploadFile.ts
  server/package-lock.json
  server/package.json
  server/router/upload/router.ts
  server/router/upload/schema.ts
  server/types/upload/types.ts
  server/utils/upload/utils.ts
Labels: backend

#20 🧪 test : upload webhook
  client/src/components/Navbar/Navbar.tsx
  client/tailwind.config.ts
  server/app.ts
  server/config/cloudinaryConfig.ts
  server/controllers/upload/NotificationWebhook.ts
  server/controllers/upload/UploadFile.ts
Labels: backend

#23 🧪 test : testing webhook when a whitelist arr is given for cors
  server/app.ts
  server/router/upload/router.ts
Labels: backend

#24 🧪 test : testing with custom cors disabling cors for upload webhook route
  server/app.ts
  server/router/upload/router.ts
Labels: backend

#25 🧪 test: testing upload route with webhook
  server/config/cloudinaryConfig.ts
  server/controllers/upload/UploadFile.ts
Labels: backend

#27 ✨ feat : file upload (API integration)
  client/src/Root.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/components/ui/file-input.tsx
  client/src/constants/dropDownOptions/index.ts
  client/src/constants/dropDownOptions/navDropDown.ts
  client/src/constants/dropDownOptions/sidebarDropDown.tsx
  client/src/constants/routes.ts
  client/src/constants/shared.ts
  client/src/hooks/useMultiStepForm.ts
  client/src/pages/DashBoard/FileUpload/FileUpload.tsx
  client/src/pages/DashBoard/FileUpload/Steps/FileInfo.tsx
  client/src/pages/DashBoard/FileUpload/Steps/FinalSubmit.tsx
  client/src/pages/DashBoard/FileUpload/Steps/Upload.tsx
  client/src/schemas/uploadSchema.ts
  client/src/types/folder.ts
  client/src/utils/axiosReqObjects/fileUpload.ts
  client/src/utils/axiosReqObjects/folder.ts
  client/src/utils/fetcher/fetcher.ts
Labels: frontend

#28 🐛 bug : user can send req to add a file to a bookmark folder multiple times but the file would be added once
  server/controllers/bookmark/AddToBookMark.ts
Labels: backend

#29 🐛 bug : search results would only those files whose upload process is complete
  server/app.ts
  server/constants/constants/upload.ts
  server/controllers/upload/NotificationWebhook.ts
  server/models/question.ts
  server/utils/search/getter.ts
  server/utils/upload/utils.ts
Labels: bug, backend

#30 🐛 bug : institution name and status is returned as response
  server/controllers/folders/GetFiles.ts
  server/utils/upload/utils.ts
Labels: bug, backend

#18 ✨ 🚀 [Feat.] Preview Page
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/Root.tsx
  client/src/components/Navbar/Navbar.tsx
  client/src/components/ReportModal/ReportModal.tsx
  client/src/constants/routes.ts
  client/src/constants/shared.ts
  client/src/pages/Preview/Comments/Comments.tsx
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Preview/PreviewContent/BookmarksModal/BookmarksModal.tsx
  client/src/pages/Preview/PreviewContent/PDFViewer/PDFViewer.tsx
  client/src/pages/Preview/PreviewContent/PreviewContent.tsx
  client/src/pages/Preview/PreviewContent/RatingPopover/RatingPopover.tsx
  client/src/pages/Search/Search.tsx
  client/src/types/bookmarks.ts
  client/src/types/file.ts
  client/src/types/ratiing.ts
  client/src/types/report.ts
  client/src/utils/axiosReqObjects/bookmarks.ts
  client/src/utils/axiosReqObjects/file.ts
  client/src/utils/axiosReqObjects/index.ts
  client/src/utils/axiosReqObjects/rating.ts
  client/src/utils/axiosReqObjects/report.ts
Labels: frontend

#32 ✨🚀[feat.] Bookmarks
  client/src/components/Skeleton.tsx
  client/src/components/TabularView/TabularFileView.tsx
  client/src/components/TabularView/TabularFolderView.tsx
  client/src/constants/routes.ts
  client/src/constants/shared.ts
  client/src/main.tsx
  client/src/pages/DashBoard/Bookmarks/Bookmarks.tsx
  client/src/pages/DashBoard/FileUpload/FileUpload.tsx
  client/src/pages/DashBoard/FileUpload/FileUploadForm/FileUploadForm.tsx
  client/src/pages/DashBoard/FileUpload/FileUploadForm/Steps/FileInfo.tsx
  client/src/pages/DashBoard/FileUpload/FileUploadForm/Steps/FinalSubmit.tsx
  client/src/pages/DashBoard/FileUpload/FileUploadForm/Steps/Upload.tsx
  client/src/types/folder.ts
  client/src/utils/axiosReqObjects/file.ts
  client/src/utils/axiosReqObjects/folder.ts
  client/src/utils/axiosReqObjects/index.ts
  client/src/utils/helpers/index.ts
  server/controllers/folders/GetFiles.ts
Labels: backend

#33 🚀 feat: pin files feat implemented
  server/constants/constants/filePreview.ts
  server/controllers/folders/GetPinnedFiles.ts
  server/controllers/folders/PinFile.ts
  server/controllers/folders/index.ts
  server/models/files.ts
  server/router/folder/router.ts
  server/router/folder/schema.ts
  server/utils/folders/sanitizeFilesInfo.ts
Labels: backend

#34 🚀 feat : admin stats
  server/controllers/upload/GetStats.ts
  server/controllers/upload/index.ts
  server/router/upload/router.ts
Labels: backend

#38 🐛 bug : bug fixes in various controllers
  server/app.ts
  server/constants/constants/search.ts
  server/controllers/filePreview/data/DeleteFile.ts
  server/controllers/filePreview/data/EditTags.ts
  server/controllers/filePreview/data/GetFile.ts
  server/middlewares/validate.ts
  server/models/question.ts
  server/package-lock.json
  server/package.json
  server/router/filePreview/data/router.ts
  server/router/filePreview/data/schema.ts
  server/utils/filePreview/deleteFileHelpers.ts
  server/utils/search/getter.ts
Labels: backend

#39 ✨[UI] Home Page
  client/package-lock.json
  client/package.json
  client/src/assets/home-page-images/features-03-image-01.png
  client/src/assets/home-page-images/features-03-image-02.png
  client/src/assets/home-page-images/features-03-image-03.png
  client/src/assets/home-page-images/hero-image-01.jpg
  client/src/assets/home-page-images/testimonial-01.jpg
  client/src/assets/home-page-images/testimonial-02.jpg
  client/src/assets/home-page-images/testimonial-03.jpg
  client/src/pages/Home/Features/Features.tsx
  client/src/pages/Home/Header/Header.tsx
  client/src/pages/Home/Header/MobileMenu/MobileMenu.tsx
  client/src/pages/Home/Hero/Hero.tsx
  client/src/pages/Home/HeroBanner/ChatBox.tsx
  client/src/pages/Home/HeroBanner/HeroBanner.tsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/Newsletter/Newsletter.tsx
  client/src/pages/Home/PageIllustration/PageIllustration.tsx
  client/src/pages/Home/Testimonials/Testimonials.tsx
  client/src/pages/Home/Zigzag/Zigzag.tsx
  client/src/pages/Home/additional-styles/range-slider.css
  client/src/pages/Home/additional-styles/theme.css
  client/src/pages/Home/additional-styles/toggle-switch.css
  client/src/pages/Home/additional-styles/utility-patterns.css
Labels: frontend
