Repository Bismay5467/ExamArchive, pull requests merged in 2024-05, with the labels that each got.

#5 Footer and Routes are ready
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Root.tsx
  client/src/assets/404.jpg
  client/src/components/Footer/Footer.tsx
  client/src/constants/socialLinks.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/404/Error.tsx
  client/src/pages/DashBoard/DashBoard.tsx
  client/src/pages/Home/HeroBanner/ChatBox.tsx
  client/src/pages/Home/HeroBanner/HeroBanner.tsx
  client/src/pages/Loading/Loading.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Preview/Preview.tsx
  client/src/pages/Search/Search.tsx
  client/src/pages/Signup/Signup.tsx
Labels: frontend

#7 Nav bar
  client/package-lock.json
  client/package.json
  client/src/components/Navbar/Navbar.tsx
  client/src/components/ui/drawer.tsx
  client/src/main.tsx
  client/src/types/index.ts
Labels: frontend

#10 🌍 ✈️ migration : migration from TRPC to REST APIs
  server/app.ts
  server/config/resendConfig.ts
  server/controllers/auth/NewUser.ts
  server/controllers/auth/Reset.ts
  server/controllers/auth/SignIn.ts
  server/controllers/bookmark/AddToBookMark.ts
  server/controllers/bookmark/RemoveBookMark.ts
  server/controllers/filePreview/comments/DeleteComment.ts
  server/controllers/filePreview/comments/EditComment.ts
  server/controllers/filePreview/comments/GetComment.ts
  server/controllers/filePreview/comments/PostComment.ts
  server/controllers/filePreview/comments/ReactOnComments.ts
  server/controllers/filePreview/data/DeleteFile.ts
  server/controllers/filePreview/data/DownloadCount.ts
  server/controllers/filePreview/data/EditTags.ts
  server/controllers/filePreview/data/GetFile.ts
  server/controllers/filePreview/data/Rating.ts
  server/controllers/filePreview/data/ViewCount.ts
  server/controllers/folders/CreateFolder.ts
  server/controllers/folders/DeleteFolder.ts
  server/controllers/folders/GetFiles.ts
  server/controllers/folders/GetFolderNames.ts
  server/controllers/folders/index.ts
  server/controllers/search/GetPapers.ts
  server/controllers/search/GetSubjectFilters.ts
  server/controllers/search/index.ts
  server/controllers/upload/NotificationWebhook.ts
  server/controllers/upload/StoreNamesInCache.ts
  server/controllers/upload/UploadFile.ts
  server/controllers/upload/index.ts
  server/emails/ContentTakeDown.tsx
  server/jobs/sendMails.ts
  server/middlewares/validate.ts
  server/middlewares/verifyUser.ts
  server/router/auth/router.ts
  server/router/bookmark/router.ts
  server/router/filePreview/comments/router.ts
  server/router/filePreview/comments/schema.ts
  server/router/filePreview/data/router.ts
  server/router/filePreview/data/schema.ts
  server/router/folder/router.ts
  server/router/folder/schema.ts
  server/router/index.ts
  server/router/search/router.ts
  server/router/search/schema.ts
  server/router/upload/router.ts
  server/router/upload/schema.ts
  server/types/filePreview/types.ts
  server/types/folders/types.ts
  server/types/search/types.ts
  server/types/upload/types.ts
  server/utils/errors/asyncErrorHandler.ts
  server/utils/errors/errorHandler.ts
  server/utils/filePreview/getComment.ts
  server/utils/search/getter.ts
  server/utils/upload/utils.ts
Labels: backend, migration

#11 ✨ feat : super admin privileged routes added
  server/constants/constants/auth.ts
  server/controllers/admin/AddAdmin.ts
  server/controllers/admin/GetAllAdmins.ts
  server/controllers/admin/RemoveAdmin.ts
  server/controllers/admin/index.ts
  server/controllers/auth/SignIn.ts
  server/controllers/filePreview/comments/ReactOnComments.ts
  server/controllers/report/MarkAsResolved.ts
  server/controllers/report/ReportContent.ts
  server/controllers/report/ViewReport.ts
  server/controllers/superadmin/Add.ts
  server/controllers/superadmin/Get.ts
  server/controllers/superadmin/Remove.ts
  server/controllers/superadmin/index.ts
  server/controllers/upload/StoreNamesInCache.ts
  server/controllers/upload/UploadFile.ts
  server/emails/ContentTakeDown.tsx
  server/emails/NotifyUserOnBeingAdmin.tsx
  server/emails/ReportNotification.tsx
  server/middlewares/previlege.ts
  server/models/user.ts
  server/router/admin/router.ts
  server/router/admin/schema.ts
  server/router/auth/router.ts
  server/router/index.ts
  server/router/report/router.ts
  server/router/report/schema.ts
  server/router/superadmin/router.ts
  server/router/superadmin/schema.ts
  server/router/upload/router.ts
  server/types/auth/types.ts
  server/utils/admin/getAdminInfo.ts
  server/utils/errors/errorHandler.ts
  server/utils/superadmin/getPassword.ts
  server/utils/superadmin/getSuperAdminInfo.ts
Labels: backend

#12 🌍✈️ migration : migration from trigger dev to resend for sending emails
  server/app.ts
  server/config/resendConfig.ts
  server/jobs/sendMails.ts
  server/router/auth/schema.ts
  server/utils/emails/sendMail.ts
Labels: backend, migration

#13 🐛 bug : search query params fixed
  server/controllers/auth/SignIn.ts
  server/controllers/search/GetPapers.ts
  server/controllers/search/GetSubjectFilters.ts
  server/router/search/schema.ts
  server/types/search/types.ts
  server/utils/search/getter.ts
Labels: bug, backend

#14 ✨ feat : route added to update the cache with admin and super admin details
  server/controllers/superadmin/UpdateCache.ts
  server/controllers/superadmin/index.ts
  server/router/search/schema.ts
  server/router/superadmin/router.ts
  server/router/superadmin/schema.ts
Labels: backend
